name: Sbuild Debian Package
description: (Cross-)Build a debian package using sbuild
branding:
  icon: package
inputs:
  distro:
    description: Which Debian distribution to use
    required: false
    default: buster
  arch:
    description: Host architecture to build the package
    required: false
    default: amd64
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/build.sh
      shell: bash
      env:
        INPUTS_DISTRO: ${{ inputs.distro }}
        INPUTS_ARCH: ${{ inputs.arch }}