name: Sbuild Debian Package
description: (Cross-)Build a debian package using sbuild
branding:
  icon: package
inputs:
  distro:
    description: Which Debian distribution to use
    required: false
    default: buster
  arch:
    description: Host architecture to build the package
    required: false
    default: amd64
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.distro }}
    - ${{ inputs.arch }}